# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use same key for each machine
  config.ssh.insert_key = false

  config.vm.define "web1" do |web1|
    web1.vm.box = "centos/7"
    web1.vm.network "forwarded_port", guest: 80, host: 8080
    web1.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.define "web2" do |web2|
    web2.vm.box = "centos/7"
    web2.vm.network "forwarded_port", guest: 80, host: 8081
    web2.vm.network "forwarded_port", guest: 443, host: 8444
  end
  config.vm.define "web3" do |web3|
    web3.vm.box = "centos/7"
    web3.vm.network "forwarded_port", guest: 80, host: 8082
    web3.vm.network "forwarded_port", guest: 443, host: 8445
  end
end
